### PR TITLE
refactor function names

### PR DESCRIPTION
**Pull request by cprogrammer1994**
### Changed

- Renamed `create_look_at` to `create_look_at_matrix`
- Kept `create_look_at` and marked as `TODO: mark as deprecated`

### Reason

There are similar functions:

- create_perspective_projection_matrix
- create_perspective_projection_matrix_from_bounds
- create_orthogonal_projection_matrix
- **create_look_at_matrix**

### CODE REVIEW

**Comment by adamlwgriffiths** [comment]
Nicely done.

I find the `_matrix` redundant considering it's already in the `matrix*` module, but apparently I've already used that for other functions. Oh well, when in Rome.

**Comment by cprogrammer1994** [comment]
I can mark those as deprecated and rename them.

**Comment by cprogrammer1994** [comment]
tests from the master also pass
```
=================== 416 passed, 19 skipped in 1.12 seconds ====================
```

**Comment by adamlwgriffiths** [comment]
Nice.
You don't need my permission to merge these. I gave your account access to do that, so feel free to make modifications and merge them as you see fit.

Again, thank you very much for your work on these.
I am sorry that I haven't been able to contribute any more than being an "armchair general" =P.

**Comment by cprogrammer1994** [comment]
merging thanks!

**Pull request merged**
