### PR TITLE
fix unused dtype

### PR DESCRIPTION
**Pull request by cprogrammer1994**

### CODE REVIEW

**Comment by cprogrammer1994** [comment]
currently

```
proj = pyrr.matrix44.create_perspective_projection_matrix(45.0, 1.0, 0.1, 1000.0, dtype=np.float32)
view = pyrr.matrix44.create_from_translation(np.array([100, 100, 100]), dtype=np.float32)
print(len(bytes(proj * view)))
```

Outputs 128

**Comment by cprogrammer1994** [comment]
Fails due to `ERROR: You need Python 2.7 or 3.3+ to install the typing package.`

**Comment by adamlwgriffiths** [comment]
Good find.
The issue is travis is pulling sphinx during the build. I'll move sphinx into it's own requirements-*.txt which will fix this error.

**Comment by adamlwgriffiths** [comment]
Should be fixed in b23000679c233981b3a3c91dec7cedc9570d5f03

It would be good if you could add a basic test for this pull request.
Ie. ensure the dtype was passed through.

**Comment by adamlwgriffiths** [comment]
I've dropped Python 3.2 from the travis config, but it's still trying to build for it. I'm not sure if there's any way I can make it stop trying 3.2.

So technically this test passes.

If you can add a test for this pull request I'll merge it.
Thanks =)

**Comment by cprogrammer1994** [comment]
Travis fails using Python 2.7

```
AssertionError: 204 != 64
```

It means that:

```
m1 = matrix44.create_perspective_projection_matrix(90, 1024./768., 1., 10., dtype='float32')
len(bytes(m1)) == 204
```

Is it possible I misunderstood how to convert numpy arrays to bytes?

**Comment by cprogrammer1994** [comment]
At least on windows the size is closer to `64` 🤣 

```python
# Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
# Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = np.array([1.0] * 16, dtype='float32')
>>> a
array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.], dtype=float32)
>>> len(bytes(a))
65
```

**Comment by adamlwgriffiths** [comment]
You can just assert that the resulting dtype is what is expected

ie. `a.dtype == np.float32`

**Comment by cprogrammer1994** [comment]
I already added using `tobytes`

**Comment by cprogrammer1994** [comment]
changed size check to dtype check

**Comment by adamlwgriffiths** [comment]
Sweet, thanks for your contribution =)

**Pull request merged**
