### PR TITLE
Quaternion slerp

### PR DESCRIPTION
**Pull request by cprogrammer1994**
- [x] imlementation
- [x] OO implementation
- [x] tests

### CODE REVIEW

**Comment by adamlwgriffiths** [comment]
Thanks again for all your work =)

We should look at doing a release soon of all your new features. Do you have a PyPi account?

**Comment by cprogrammer1994** [comment]
yes, cprogrammer1994 add me as a maintainer

**Comment by adamlwgriffiths** [comment]
Ok, I added you as 'maintainer' on PyPi, hopefully that is sufficient to make a release.
I updated the [CHANGELOG.md](https://github.com/adamlwgriffiths/Pyrr/blob/master/CHANGELOG.md) file.
Bumped version in [version.py](https://github.com/adamlwgriffiths/Pyrr/blob/master/pyrr/version.py) to 0.9.0.
Tagged the repo and made a ['release'](https://github.com/adamlwgriffiths/Pyrr/releases/tag/0.9.0).

Would you like to take the latest repo and push the package to PyPi?
You can just run `bash scripts/upload_package.sh` and it should do it for you.

**Comment by adamlwgriffiths** [comment]
Did you get around to pushing it? PyPi still reports 0.8.4 as the latest
https://pypi.python.org/pypi/pyrr

**Comment by cprogrammer1994** [comment]
I am travelling right now. I will not be able to do this soon. Please release i'll try the next one.

**Comment by cprogrammer1994** [comment]
done [0.9.0](https://pypi.python.org/pypi/pyrr/0.9.0)

**Comment by cprogrammer1994** [comment]
tested pip:
```
Python27-32\python.exe -m pip install pyrr==0.9.0
Collecting pyrr==0.9.0
  Downloading pyrr-0.9.0-py2.py3-none-any.whl (64kB)
    100% |################################| 71kB 669kB/s
Collecting multipledispatch (from pyrr==0.9.0)
  Using cached multipledispatch-0.4.9-py2.py3-none-any.whl
Collecting numpy (from pyrr==0.9.0)
  Using cached numpy-1.13.0-cp27-none-win32.whl
Installing collected packages: multipledispatch, numpy, pyrr
Successfully installed multipledispatch-0.4.9 numpy-1.13.0 pyrr-0.9.0

Python27-64\python.exe -m pip install pyrr==0.9.0
Collecting pyrr==0.9.0
  Using cached pyrr-0.9.0-py2.py3-none-any.whl
Collecting multipledispatch (from pyrr==0.9.0)
  Using cached multipledispatch-0.4.9-py2.py3-none-any.whl
Collecting numpy (from pyrr==0.9.0)
  Downloading numpy-1.13.0-cp27-none-win_amd64.whl (7.6MB)
    100% |################################| 7.6MB 160kB/s
Installing collected packages: multipledispatch, numpy, pyrr
Successfully installed multipledispatch-0.4.9 numpy-1.13.0 pyrr-0.9.0

Python35-32\python.exe -m pip install pyrr==0.9.0
Collecting pyrr==0.9.0
  Using cached pyrr-0.9.0-py2.py3-none-any.whl
Collecting multipledispatch (from pyrr==0.9.0)
  Using cached multipledispatch-0.4.9-py2.py3-none-any.whl
Collecting numpy (from pyrr==0.9.0)
  Using cached numpy-1.13.0-cp35-none-win32.whl
Installing collected packages: multipledispatch, numpy, pyrr
Successfully installed multipledispatch-0.4.9 numpy-1.13.0 pyrr-0.9.0

Python35-64\python.exe -m pip install pyrr==0.9.0
Collecting pyrr==0.9.0
  Using cached pyrr-0.9.0-py2.py3-none-any.whl
Collecting multipledispatch (from pyrr==0.9.0)
  Using cached multipledispatch-0.4.9-py2.py3-none-any.whl
Collecting numpy (from pyrr==0.9.0)
  Downloading numpy-1.13.0-cp35-none-win_amd64.whl (7.8MB)
    100% |################################| 7.8MB 156kB/s
Installing collected packages: multipledispatch, numpy, pyrr
Successfully installed multipledispatch-0.4.9 numpy-1.13.0 pyrr-0.9.0

Python36-32\python.exe -m pip install pyrr==0.9.0
Collecting pyrr==0.9.0
  Using cached pyrr-0.9.0-py2.py3-none-any.whl
Collecting numpy (from pyrr==0.9.0)
  Using cached numpy-1.13.0-cp36-none-win32.whl
Collecting multipledispatch (from pyrr==0.9.0)
  Using cached multipledispatch-0.4.9-py2.py3-none-any.whl
Installing collected packages: numpy, multipledispatch, pyrr
Successfully installed multipledispatch-0.4.9 numpy-1.13.0 pyrr-0.9.0

Python36-64\python.exe -m pip install pyrr==0.9.0
Collecting pyrr==0.9.0
  Using cached pyrr-0.9.0-py2.py3-none-any.whl
Collecting multipledispatch (from pyrr==0.9.0)
  Using cached multipledispatch-0.4.9-py2.py3-none-any.whl
Collecting numpy (from pyrr==0.9.0)
  Downloading numpy-1.13.0-cp36-none-win_amd64.whl (7.8MB)
    100% |████████████████████████████████| 7.8MB 155kB/s
Installing collected packages: multipledispatch, numpy, pyrr
Successfully installed multipledispatch-0.4.9 numpy-1.13.0 pyrr-0.9.0
```

**Comment by adamlwgriffiths** [comment]
Thanks!
Apologies, I was busy and unable to do the release.
After this coming week I should have time to help out.

**Comment by cprogrammer1994** [comment]
Thanks!

I will add Pyrr to ModernGL vscode snippets by default 😄 I will provide 2D and 3D examples too.
I'll tell you when it is done. I am lucky that Pyrr exists. It helps my development!

**Pull request merged**
