### PR TITLE
Remove Python 2.6 Support

### PR DESCRIPTION
**Pull request by foohyfooh**

### CODE REVIEW

**Comment by foohyfooh** [comment]
Fixes #75

**Comment by adamlwgriffiths** [comment]
Any clues as to why 3.5 is broken?
Strange that 3.3, 3.4, and 3.6 are all fine. Did numpy break something?

**Comment by foohyfooh** [comment]
The issue seems to happen with numpy==1.15.0. I had numpy==1.14.5 installed on my machine so I did get the error when testing locally.
I will have to investigate more and possibly file a bug in numpy.

**Comment by foohyfooh** [comment]
The issue filed with numpy can be found at https://github.com/numpy/numpy/issues/11743

**Comment by adamlwgriffiths** [comment]
I think we can consider that a separate issue.

**Comment by adamlwgriffiths** [comment]
Added new issue for this: #77

**Pull request merged**
