### PR TITLE
Add quaternion exp method

### PR DESCRIPTION
**Pull request by foohyfooh**

### CODE REVIEW

**Comment by adamlwgriffiths** [comment]
I don't pretend to understand Quaternion maths so I can't comment on the correctness.
If you believe it is correct then please feel free to merge.

**Comment by foohyfooh** [comment]
I am still learning and trying to understand quaternion maths so I am in a similar boat as you. I believe it is correct but it would be preferable to have someone look it over.

**Comment by foohyfooh** [comment]
@cprogrammer1994  Do you understand it well enough to comment on the correctness?

**Comment by adamlwgriffiths** [comment]
My only suggestion would be to see if there are any formal tests for the exp function.
One of the mistakes I made previously was not including validation for first principles in the tests.

There may be value in some of these links:
https://reference.wolfram.com/language/ref/Exp.html
https://cs.brown.edu/~jwicks/boost/libs/math/quaternion/quaternion_test.cpp

**Comment by foohyfooh** [comment]
I added addition tests. Just need approval to merge

**Pull request merged**
