### PR TITLE
Made create_from_eulers use configurable order from euler.py

### PR DESCRIPTION
**Pull request by ubald**

### CODE REVIEW

**Comment by Korijn** [comment]
LGTM.

A regression test might be nice but we can merge if you feel this is done.

**Comment by ubald** [comment]
I wondered why all tests passed, they haven't been implemented for quaternion creation from eulers. Let me add the test to the PR.

**Comment by ubald** [comment]
I have added tests but unfortunately I don't really get what `create_from_inverse_of_eulers` is supposed to mean so I couldn't write a test for it.

**Comment by Korijn** [comment]
Thanks!

**Comment by adamlwgriffiths** [comment]
Inverse should just be the opposite of the rotation provided.

Apologies for not being around, Github isn't sending me _any_ notifications for this repository anymore =/

**Pull request merged**
