### PR TITLE
Add methods to create a quaternion from an axis

### PR DESCRIPTION
**Pull request by foohyfooh**

### CODE REVIEW

**Comment by cprogrammer1994** [comment]
Looks good to me.

**Comment by cprogrammer1994** [comment]
Please add some tests.

**Comment by cprogrammer1994** [comment]
I think we can merge it.

@adamlwgriffiths

**Comment by adamlwgriffiths** [comment]
I'll check it out tonight. 
Call me stupid, but what rotation does this create?
May need to clarify in the doc string.

**Comment by adamlwgriffiths** [comment]
I'm not in a position to merge as I don't understand the `linalg.norm` function.
Is it taking a vector length and using the magnitude as the rotation about the axis?

The code quality is fine though.
@cprogrammer1994, If you believe the maths are sound then feel free to merge.

**Comment by foohyfooh** [comment]
You are correct. The vector length of the unnormalided axis is being used as the magnitude of rotation. 
```numpy.linalg.norm``` by default takes the Frobenius norm of the vector which the magnitude of the vector.

Sorry for not making that more prominent.

**Comment by adamlwgriffiths** [comment]
All good, it's just showing my lack of knowledge.
Thanks for your contribution =)

**Comment by cprogrammer1994** [comment]
An example would be [Angular velocity](https://en.wikipedia.org/wiki/Angular_velocity) that can be quickly turned into a quaternion using this method. The resulting quaterion can be used to apply a rotation per simulation tick to a given object.

**Pull request merged**
