### PR TITLE
Affine matrix decomposition

### PR DESCRIPTION
**Pull request by Korijn**
This function decomposes an affine matrix44 into its scale, rotation and translation components.

### CODE REVIEW

**Comment by adamlwgriffiths** [comment]
Hi Korijn,
I've added you as a collaborator so you can collaborate more effectively.
Thanks for your help =)

**Comment by cprogrammer1994** [comment]
Welcome aboard :)

**Comment by Korijn** [comment]
I am honored. :) Thanks!

**Comment by adamlwgriffiths** [comment]
lol, you've both contributed great code, so it is I who am honored to know this library is in good hands =)

**Comment by Korijn** [comment]
Good thing I checked, fixed 2 more bugs. :)

**Pull request merged**
